<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->insert([
            [
                'id' => 1,
                'name' => "Espada ancha",
                'description' => "Una espada de hoja recta, de empuñadura rendonda y más corta que una espada larga.",
                'attack_modifier' => 4,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => "Alfanje",
                'description' => "De hoja ancha y curvada, y con una empuñadura redonda, este arma es la preferida de los piratas de las costas de Zalthoria",
                'attack_modifier' => 3,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3, 'name' => "Maza de pinchos", 'description' => "Una maza de acero con pinchos en su cabeza, ideal para destrozar armaduras y huesos por igual.",
                'attack_modifier' => 4,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 4, 'name' => "Arco corto", 'description' => "Un arco compacto y fácil de manejar, perfecto para ataques rápidos a distancia en terrenos cerrados.",
                'attack_modifier' => 3,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 5, 'name' => "Daga de asesino", 'description' => "Una daga ligera y afilada, empleada por asesinos y ladrones que buscan la discreción y velocidad.",
                'attack_modifier' => 3,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 6, 'name' => "Lanza corta", 'description' => "Una lanza de alcance medio con una punta afilada, utilizada por infanterías ligeras en formaciones cerradas.",
                'attack_modifier' => 3,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 7, 'name' => "Cuchillo de combate", 'description' => "Un cuchillo robusto y versátil, adecuado tanto para el combate cuerpo a cuerpo como para lanzarlo a corta distancia.",
                'attack_modifier' => 2,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 8, 'name' => "Martillo de guerra", 'description' => "Un martillo pesado con una cabeza contundente y un pico al otro extremo, perfecto para luchar contra enemigos fuertemente armados.",
                'attack_modifier' => 5,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 9, 'name' => "Hacha de mano", 'description' => "Un hacha ligera y fácil de manejar, diseñada para cortar y desgarrar carne y armaduras.",
                'attack_modifier' => 3,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 10, 'name' => "Bastón de madera", 'description' => "Un bastón sencillo y resistente, utilizado por magos y druidas en combate cuerpo a cuerpo.",
                'attack_modifier' => 1,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 11, 'name' => "Garrote", 'description' => "Un garrote contundente, hecho de madera sólida y reforzado con hierro para infligir más daño.",
                'attack_modifier' => 2,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 12, 'name' => "Espada corta", 'description' => "Una espada corta y ligera, perfecta para golpes rápidos y precisos en el combate cercano.",
                'attack_modifier' => 3,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 13, 'name' => "Ballesta", 'description' => "Una ballesta de mano, capaz de disparar proyectiles mortales a largas distancias.",
                'attack_modifier' => 4,
                'defense_modifier' => 0,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 14, 'name' => "Cetro místico", 'description' => "Un cetro adornado con gemas y runas, utilizado por magos y hechiceros para canalizar su energía.",
                'attack_modifier' => 3,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => "Armadura de cuero",
                'description' => "Una armadura ligera hecha de cuero endurecido, ofrece cierta protección y permite una buena movilidad.",
                'attack_modifier' => 1,
                'defense_modifier' => 4,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => "Escudo de madera",
                'description' => "Un escudo ligero y resistente hecho de madera, útil para bloquear ataques enemigos.",
                'attack_modifier' => 1,
                'defense_modifier' => 4,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => "Armadura de malla",
                'description' => "Una armadura intermedia hecha de anillos de metal entrelazados, ofrece una protección moderada y conserva cierta movilidad.",
                'attack_modifier' => 2,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => "Casco de hierro",
                'description' => "Un casco sólido hecho de hierro, protege la cabeza de golpes y cortes.",
                'attack_modifier' => 1,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => "Grebas de cuero",
                'description' => "Protecciones para las piernas hechas de cuero endurecido, ofrecen protección básica y no limitan la movilidad.",
                'attack_modifier' => 1,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => "Brazales de hierro",
                'description' => "Protectores sólidos para los brazos hechos de hierro, ofrecen una buena defensa contra ataques enemigos.",
                'attack_modifier' => 1,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => "Cimitarra",
                'description' => "Una espada curva de un solo filo, ideal para cortar con precisión.",
                'attack_modifier' => 4,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => "Hacha de mano",
                'description' => "Un hacha pequeña y ligera, diseñada para el combate cercano y arrojar a corta distancia.",
                'attack_modifier' => 3,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => "Ballesta ligera",
                'description' => "Una ballesta compacta y fácil de manejar, perfecta para ataques rápidos a distancia.",
                'attack_modifier' => 4,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => "Mandoble",
                'description' => "Una espada de dos manos de gran tamaño, capaz de infligir daño devastador.",
                'attack_modifier' => 5,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => "Coraza de acero",
                'description' => "Una armadura pesada hecha de placas de acero, ofrece gran protección a expensas de la movilidad.",
                'attack_modifier' => 1,
                'defense_modifier' => 4,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => "Escudo redondo",
                'description' => "Un escudo circular hecho de metal, proporciona una defensa sólida contra ataques enemigos.",
                'attack_modifier' => 1,
                'defense_modifier' => 4,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => "Bastón de combate",
                'description' => "Un bastón sólido y ligero, utilizado por monjes y luchadores versátiles.",
                'attack_modifier' => 3,
                'defense_modifier' => 2,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => "Armadura de escamas",
                'description' => "Una armadura intermedia hecha de escamas de metal superpuestas, ofrece una protección balanceada y cierta movilidad.",
                'attack_modifier' => 2,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => "Bumerán",
                'description' => "Un arma arrojadiza de madera o metal que regresa a su lanzador tras ser arrojada.",
                'attack_modifier' => 3,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => "Garrote pesado",
                'description' => "Un palo largo y pesado, utilizado como arma contundente.",
                'attack_modifier' => 4,
                'defense_modifier' => 1,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => "Casco de cuero",
                'description' => "Un casco ligero hecho de cuero endurecido, protege la cabeza de golpes leves.",
                'attack_modifier' => 1,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => "Brigantina",
                'description' => "Una armadura de cuero reforzada con placas de metal, ofrece protección sin sacrificar demasiado la movilidad.",
                'attack_modifier' => 1,
                'defense_modifier' => 4,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => "Escudo de madera",
                'description' => "Un escudo ligero hecho de madera, proporciona una defensa básica contra ataques enemigos.",
                'attack_modifier' => 1,
                'defense_modifier' => 3,
                'rare' => 'comun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => "Cimitarra afilada",
                'description' => "Una cimitarra con un filo excepcionalmente afilado, capaz de cortar a través de la armadura enemiga.",
                'attack_modifier' => 5,
                'defense_modifier' => 2,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => "Arco largo encantado",
                'description' => "Un arco largo imbuido de poderes mágicos, aumentando su alcance y precisión.",
                'attack_modifier' => 6,
                'defense_modifier' => 1,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => "Hacha de guerra en llamas",
                'description' => "Un hacha de guerra que arde con un fuego místico, infligiendo daño adicional por quemaduras.",
                'attack_modifier' => 7,
                'defense_modifier' => 1,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => "Martillo de trueno",
                'description' => "Un martillo mágico que emite relámpagos al golpear, causando daño adicional por choque eléctrico.",
                'attack_modifier' => 6,
                'defense_modifier' => 2,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => "Armadura pesada brillante",
                'description' => "Una armadura de placas de metal pulido que brilla intensamente, reflejando los ataques enemigos y deslumbrando a los oponentes.",
                'attack_modifier' => 2,
                'defense_modifier' => 6,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => "Escudo espectral",
                'description' => "Un escudo místico que puede absorber el daño mágico, protegiendo a su portador de hechizos y conjuros.",
                'attack_modifier' => 1,
                'defense_modifier' => 7,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => "Armadura de escamas de dragón",
                'description' => "Una armadura forjada a partir de escamas de dragón, proporciona una defensa excepcional y resistencia a los elementos.",
                'attack_modifier' => 2,
                'defense_modifier' => 7,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => "Espada de hielo",
                'description' => "Una espada mágica que emana un frío intenso, capaz de congelar a sus enemigos con cada golpe.",
                'attack_modifier' => 6,
                'defense_modifier' => 2,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => "Bastón de la tormenta",
                'description' => "Un bastón imbuido de la fuerza de una tormenta, lanzando rayos a los enemigos cercanos.",
                'attack_modifier' => 6,
                'defense_modifier' => 1,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => "Lanza de viento cortante",
                'description' => "Una lanza afilada que canaliza el poder del viento, generando ráfagas cortantes con cada ataque.",
                'attack_modifier' => 7,
                'defense_modifier' => 1,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => "Daga de sombras",
                'description' => "Una daga envuelta en oscuridad, capaz de atravesar las defensas enemigas y debilitar a sus objetivos.",
                'attack_modifier' => 6,
                'defense_modifier' => 1,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => "Capa de invisibilidad",
                'description' => "Una capa mágica que otorga invisibilidad temporal a su portador, permitiendo evadir ataques enemigos con facilidad.",
                'attack_modifier' => 1,
                'defense_modifier' => 6,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => "Casco de la mente serena",
                'description' => "Un casco especial que protege a su portador de los ataques psíquicos y la manipulación mental.",
                'attack_modifier' => 1,
                'defense_modifier' => 7,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => "Armadura de la naturaleza",
                'description' => "Una armadura forjada con materiales naturales, que otorga resistencia a los elementos y regenera lentamente la salud de su portador.",
                'attack_modifier' => 2,
                'defense_modifier' => 6,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => "Guadaña de la parca",
                'description' => "Una guadaña temible con una hoja afilada y una apariencia sombría, capaz de sembrar el miedo en los corazones de los enemigos.",
                'attack_modifier' => 7,
                'defense_modifier' => 2,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => "Botas aladas",
                'description' => "Un par de botas mágicas con alas, que otorgan a su portador una mayor agilidad y capacidad de evasión.",
                'attack_modifier' => 1,
                'defense_modifier' => 6,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => "Guanteletes de titán",
                'description' => "Un par de guanteletes que otorgan una fuerza sobrehumana a su portador, permitiendo desviar ataques y romper las defensas enemigas.",
                'attack_modifier' => 7,
                'defense_modifier' => 2,
                'rare' => 'raro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => "Espada de dragón",
                'description' => "Una espada legendaria forjada en el fuego de un dragón, capaz de desatar llamas con cada golpe.",
                'attack_modifier' => 10,
                'defense_modifier' => 2,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => "Armadura de dragón",
                'description' => "Una armadura hecha de las escamas de un dragón antiguo, brindando una protección excepcional y resistencia al fuego.",
                'attack_modifier' => 1,
                'defense_modifier' => 11,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => "Bastón de archimago",
                'description' => "Un bastón místico imbuido con el poder de los grandes magos del pasado, aumentando la potencia de los conjuros de quien lo porta.",
                'attack_modifier' => 9,
                'defense_modifier' => 4,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => "Escudo del guardián eterno",
                'description' => "Un escudo indestructible que ha protegido a los guerreros a lo largo de innumerables batallas, otorgando una defensa casi impenetrable.",
                'attack_modifier' => 1,
                'defense_modifier' => 12,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => "Hacha de titán helado",
                'description' => "Un hacha formidable que lleva el frío eterno en su filo, capaz de congelar a sus enemigos con cada impacto.",
                'attack_modifier' => 11,
                'defense_modifier' => 1,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => "Arco del viento susurrante",
                'description' => "Un arco legendario que permite a su portador disparar flechas infundidas con la fuerza de los vientos, aumentando su alcance y velocidad.",
                'attack_modifier' => 10,
                'defense_modifier' => 2,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => "Lanza de rayo celestial",
                'description' => "Una lanza imbuida con la energía de las tormentas, liberando rayos de energía eléctrica en sus enemigos.",
                'attack_modifier' => 9,
                'defense_modifier' => 3,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => "Manto de las sombras",
                'description' => "Un manto que otorga a su portador la capacidad de desvanecerse en las sombras, proporcionando una evasión y defensa inigualables.",
                'attack_modifier' => 2,
                'defense_modifier' => 10,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => "Coraza de la fortaleza",
                'description' => "Una coraza impenetrable que convierte a su portador en una fortaleza andante, resistiendo incluso los ataques más feroces.",
                'attack_modifier' => 1,
                'defense_modifier' => 11,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => "Yelmo del valiente",
                'description' => "Un yelmo que otorga coraje y resistencia sobrenaturales a su portador, aumentando su capacidad para resistir ataques y permanecer firme en la batalla.",
                'attack_modifier' => 1,
                'defense_modifier' => 12,
                'rare' => 'epico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => "Excalibur",
                'description' => "La legendaria espada de la leyenda artúrica, otorgada por la Dama del Lago. Excalibur posee un poder inigualable y brilla con luz divina en la batalla.",
                'attack_modifier' => 16,
                'defense_modifier' => 0,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => "Gungnir",
                'description' => "La lanza del dios nórdico Odín, forjada por los enanos y dotada de una precisión sobrenatural. Ningún enemigo puede escapar de la punta de Gungnir.",
                'attack_modifier' => 15,
                'defense_modifier' => 1,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => "Aegis",
                'description' => "El escudo divino portado por Atenea y Zeus en la mitología griega. Aegis brinda protección sin igual y es capaz de desatar un poderoso rayo en la batalla.",
                'attack_modifier' => 2,
                'defense_modifier' => 14,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name' => "Armadura de Aquiles",
                'description' => "La armadura del invulnerable héroe griego Aquiles, forjada por el dios Hefesto. Esta armadura otorga resistencia y agilidad excepcionales a su portador.",
                'attack_modifier' => 0,
                'defense_modifier' => 16,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name' => "Yelmo de Hades",
                'description' => "El yelmo del dios griego del inframundo, Hades. Este yelmo confiere a su portador el poder de volverse invisible y otorga una defensa mística insuperable.",
                'attack_modifier' => 1,
                'defense_modifier' => 15,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name' => "Mjolnir",
                'description' => "El martillo del dios nórdico Thor, forjado por los enanos Brokkr y Sindri. Mjölnir es capaz de generar truenos y relámpagos, y nunca falla en regresar a la mano de su dueño después de ser lanzado.",
                'attack_modifier' => 14,
                'defense_modifier' => 2,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name' => "Manto de Quetzalcóatl",
                'description' => "Un manto sagrado adornado con las brillantes plumas del dios azteca Quetzalcóatl. Este manto otorga a su portador la capacidad de volar y una protección divina.",
                'attack_modifier' => 0,
                'defense_modifier' => 16,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name' => "Cetro de Osiris",
                'description' => "Un cetro poderoso que perteneció al dios egipcio Osiris, gobernante del inframundo y dios de la vida, la muerte y la resurrección. El cetro de Osiris otorga a su portador poderes divinos y control sobre la vida y la muerte.",
                'attack_modifier' => 15,
                'defense_modifier' => 1,
                'rare' => 'legendario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
