<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonsterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('monsters')->insert([

            [
                'id' => 1,
                'name' => "Colmillo Sombrío",
                'attack' => 20,
                'defense' => 15,
                'health' => 220,
                'description' => "Un dragón de afilados colmillos, piel rosada y unos ojos dorados que se iluminan en la penumbra.",
                'monster_image_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 2,
                'name' => "Dragón abisal",
                'attack' => 18,
                'defense' => 14,
                'health' => 240,
                'description' => "Un enorme dragón de las profundidades marinas, de escamas verdes y mirada paralizante.",
                'monster_image_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'name' => "Garrasangre",
                'attack' => 16,
                'defense' => 15,
                'health' => 200,
                'description' => "Un feroz dragón cubierto de escamas venenosas, capaz de desgarrar a sus enemigos con rapidez y precisión.",
                'monster_image_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 4,
                'name' => "Espíritu Desolador",
                'attack' => 22,
                'defense' => 14,
                'health' => 260,
                'description' => "Una aparición etérea y aterradora que se alimenta del miedo y la desesperación de sus víctimas.",
                'monster_image_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 5,
                'name' => "Cuerno emergente",
                'attack' => 19,
                'defense' => 16,
                'health' => 180,
                'description' => "Una peligrosa cría de dragón, de las más grandes que has visto en las cuevas.",
                'monster_image_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 6,
                'name' => "Cría Voraz",
                'attack' => 17,
                'defense' => 14,
                'health' => 210,
                'description' => "Este pequeño dragón tiene un hambre enorme. Todos aquellos que lo han subestimado, han perecido.",
                'monster_image_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 7,
                'name' => "Cría salvaje",
                'attack' => 15,
                'defense' => 15,
                'health' => 240,
                'description' => "Sus cuernos son cortos pero sus colmillos afilados. El color esmeralda de sus escamas es capaz de deslumbrar a los incautos.",
                'monster_image_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 8,
                'name' => "Ventisca Plateada",
                'attack' => 21,
                'defense' => 14,
                'health' => 280,
                'description' => "Esta cría de dragón de aspecto delicado posee un plumaje plateado y escamas relucientes, y puede controlar el viento y el hielo a su antojo.",
                'monster_image_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 9,
                'name' => "Terratemblor",
                'attack' => 19,
                'defense' => 16,
                'health' => 200,
                'description' => "Dragón de escamas de piedra y cuernos de metal, cuyos pasos hacen temblar la tierra y cuya fuerza es capaz de mover montañas y abrir fisuras en el suelo.",
                'monster_image_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 10,
                'name' => "Rugido Solar",
                'attack' => 17,
                'defense' => 15,
                'health' => 260,
                'description' => "Un poderoso dragón de escamas doradas y resplandecientes, con una melena llameante y ojos que parecen soles ardientes, capaz de lanzar llamaradas solares.",
                'monster_image_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 11,
                'name' => "Escamadorada",
                'attack' => 22,
                'defense' => 14,
                'health' => 290,
                'description' => "Su aliento ardiente y su agilidad en el aire lo convierten en un adversario formidable y difícil de atrapar. Sus escampas son como llamas danzantes.",
                'monster_image_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 12,
                'name' => "Esmeralda Terrestre",
                'attack' => 20,
                'defense' => 15,
                'health' => 180,
                'description' => "Una pequeña pero robusta cría de dragón de tonos verdes y terrosos, con habilidades para manipular la tierra y la vegetación a su alrededor.",
                'monster_image_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 13,
                'name' => "Tormenta Umbría",
                'attack' => 14,
                'defense' => 16,
                'health' => 230,
                'description' => "Un imponente dragón de escamas negras como la noche y ojos que parecen tragar la luz, capaz de desatar poderosas tormentas eléctricas y envolver su entorno en tinieblas.",
                'monster_image_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 14,
                'name' => "Llamarada Crepuscular",
                'attack' => 16,
                'defense' => 14,
                'health' => 160,
                'description' => "Una pequeña cría de dragón de escamas marrones y ojos brillantes, capaz de lanzar destellos de fuego mágico que iluminan la noche.",
                'monster_image_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 15,
                'name' => "Bruma Esmeralda",
                'attack' => 20,
                'defense' => 15,
                'health' => 200,
                'description' => "Con escamas de un suave verde claro, este dragón parece reflejar la luz del amanecer. Es capaz de controlar las neblinas y es experto en camuflarse entre la vegetación.",
                'monster_image_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 16,
                'name' => "Guardián Terracota",
                'attack' => 18,
                'defense' => 16,
                'health' => 190,
                'description' => "De aspecto robusto este dragón se mezclan perfectamente con su entorno. Protector por naturaleza, este dragón tiene la habilidad de controlar el terreno a su alrededor.",
                'monster_image_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 17,
                'name' => "Vórtice Púrpura",
                'attack' => 22,
                'defense' => 14,
                'health' => 270,
                'description' => "Este elegante dragón posee la habilidad de manipular las energías místicas y abrir portales a otros planos. Sus ojos brillan con un aura misteriosa que intriga a quienes lo contemplan.",
                'monster_image_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 18,
                'name' => "Centinela Escarlata",
                'attack' => 17,
                'defense' => 16,
                'health' => 210,
                'description' => "Un dragón de tamaño medio con escamas rojas brillantes y cuernos afilados. Este guardián ardiente es conocido por su aliento de fuego intenso y su gran valentía al enfrentarse a los enemigos.",
                'monster_image_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 19,
                'name' => "Titán Resplandeciente",
                'attack' => 22,
                'defense' => 16,
                'health' => 340,
                'description' => "Un majestuoso dragón gigante de escamas doradas que brillan como el sol, con cuernos y garras de oro puro. Este imponente ser alado es capaz de controlar la luz y de deslumbrar a sus adversarios con su presencia fulgurante.",
                'monster_image_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 20,
                'name' => "Leviatán Carmesí",
                'attack' => 22,
                'defense' => 16,
                'health' => 340,
                'description' => "Un colosal dragón de escamas rojas como la sangre y ojos que arden con un fuego inextinguible. Este monstruo alado es capaz de desatar tormentas de fuego y lava, dejando un rastro de destrucción y desolación a su paso.",
                'monster_image_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => "Salamandra Venenosa",
                'attack' => 19,
                'defense' => 14,
                'health' => 170,
                'description' => "Un anfibio de aspecto amenazador con escamas resbaladizas y venenosas, capaz de moverse con rapidez tanto en tierra como en agua.",
                'monster_image_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 22,
                'name' => "Hombre bestia",
                'attack' => 20,
                'defense' => 15,
                'health' => 200,
                'description' => "Un hombre bestia feroz con aspecto lupino y garras afiladas, que aúlla a la luna llena y acecha a sus presas en las sombras.",
                'monster_image_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 23,
                'name' => "Minotauro Despiadado",
                'attack' => 22,
                'defense' => 16,
                'health' => 240,
                'description' => "Un hombre bestia imponente con cuerpo humanoide y cabeza astada, que embiste con furia a sus enemigos y los aplasta con su fuerza brutal.",
                'monster_image_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 24,
                'name' => "Bestia nocturna",
                'attack' => 18,
                'defense' => 14,
                'health' => 190,
                'description' => "Un hombre bestia musculoso con rasgos de oso y garras enormes, capaz de desgarrar a sus enemigos con facilidad y rugir de manera ensordecedora.",
                'monster_image_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 25,
                'name' => "Hombre Sombra",
                'attack' => 17,
                'defense' => 15,
                'health' => 180,
                'description' => "Un hombre bestia ágil y sigiloso, experto en ocultarse en las sombras y atacar a sus enemigos desde el anonimato.",
                'monster_image_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 26,
                'name' => "Goblin Arquero",
                'attack' => 16,
                'defense' => 14,
                'health' => 160,
                'description' => "Un pequeño y astuto goblin armado con un arco y flechas envenenadas, capaz de atacar a sus enemigos desde la distancia con gran precisión.",
                'monster_image_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 27,
                'name' => "Bola y Cadena",
                'attack' => 21,
                'defense' => 14,
                'health' => 175,
                'description' => "Un goblin feroz y despiadado que blande una pesada bola y cadena, capaz de infligir daño devastador a sus enemigos con un solo golpe.",
                'monster_image_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 28,
                'name' => "Goblin Chamán",
                'attack' => 15,
                'defense' => 14,
                'health' => 170,
                'description' => "Un goblin enigmático y astuto que domina las artes oscuras, capaz de lanzar hechizos malditos y debilitar a sus enemigos con sus conjuros.",
                'monster_image_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 29,
                'name' => "Jinete Lobo",
                'attack' => 18,
                'defense' => 15,
                'health' => 180,
                'description' => "Un goblin temerario montado en un lobo feroz y veloz, capaz de emboscar a sus enemigos y atacar con una velocidad y ferocidad sorprendentes.",
                'monster_image_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 30,
                'name' => "Asesino Halfling",
                'attack' => 20,
                'defense' => 14,
                'health' => 165,
                'description' => "Un halfling sigiloso y letal, experto en el arte del asesinato y en el uso de dagas envenenadas, capaz de eliminar a sus enemigos en silencio y sin dejar rastro.",
                'monster_image_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 31,
                'name' => "Gladiador escamado",
                'attack' => 20,
                'defense' => 16,
                'health' => 190,
                'description' => "Un hombre lagarto rojo con aspecto de gladiador, que porta una armadura y un tridente afilado, su destreza en la lucha y resistencia lo convierten en un adversario formidable.",
                'monster_image_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 32,
                'name' => "Guerrero Carmesí",
                'attack' => 21,
                'defense' => 15,
                'health' => 210,
                'description' => "Un feroz hombre lagarto rojo con apariencia de guerrero, armado con una espada y un escudo de escamas, su fuerza y agilidad lo convierten en un combatiente letal en el campo de batalla.",
                'monster_image_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 33,
                'name' => "Mago Escarlata",
                'attack' => 17,
                'defense' => 14,
                'health' => 180,
                'description' => "Un hombre lagarto rojo con aspecto de hechicero, adornado con ropajes místicos y un bastón de poder, capaz de lanzar hechizos devastadores y controlar las fuerzas elementales.",
                'monster_image_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 34,
                'name' => "Chamán Anfibio",
                'attack' => 15,
                'defense' => 14,
                'health' => 170,
                'description' => "Un hombre lagarto rojo con apariencia de chamán, rodeado de amuletos y talismanes, con la habilidad de invocar espíritus y conjurar maldiciones sobre sus enemigos.",
                'monster_image_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 35,
                'name' => "Arquero Anuro",
                'attack' => 17,
                'defense' => 14,
                'health' => 175,
                'description' => "Un anfibio diestro en el uso del arco y las flechas, capaz de moverse con facilidad en entornos acuáticos y terrestres, atacando a sus enemigos desde lejos.",
                'monster_image_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 36,
                'name' => "Asesino Salamandrino",
                'attack' => 20,
                'defense' => 14,
                'health' => 160,
                'description' => "Un anfibio letal y sigiloso que se especializa en asesinatos y emboscadas, utilizando sus habilidades para moverse sin ser detectado y atacar a sus enemigos por sorpresa.",
                'monster_image_id' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 37,
                'name' => "Lancero Tritón",
                'attack' => 19,
                'defense' => 15,
                'health' => 200,
                'description' => "Un anfibio poderoso y ágil armado con una larga lanza, capaz de atacar a sus enemigos desde una distancia segura, tanto en tierra como bajo el agua.",
                'monster_image_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => "Hachaz Firmez",
                'attack' => 21,
                'defense' => 15,
                'health' => 220,
                'description' => "Un orco feroz y musculoso que blande dos hachas con maestría, desatando una tormenta de golpes mortales sobre sus enemigos en combate cuerpo a cuerpo.",
                'monster_image_id' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 39,
                'name' => "Filo azezino",
                'attack' => 22,
                'defense' => 14,
                'health' => 230,
                'description' => "Un orco imponente y brutal que porta un hacha gigante, capaz de partir en dos a sus enemigos con un solo golpe y sembrar el terror en el corazón de sus adversarios.",
                'monster_image_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 40,
                'name' => "Lanza mortal",
                'attack' => 18,
                'defense' => 16,
                'health' => 210,
                'description' => "Un orco aguerrido y astuto, armado con una lanza larga y afilada, capaz de mantener a raya a sus enemigos y atacar desde una distancia segura en el campo de batalla.",
                'monster_image_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 41,
                'name' => "Orcus Chamán",
                'attack' => 17,
                'defense' => 14,
                'health' => 190,
                'description' => "Un orco misterioso y enigmático que domina la magia oscura, utilizando su poder para invocar criaturas del inframundo y lanzar maldiciones sobre sus enemigos.",
                'monster_image_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 42,
                'name' => "Esclavo arquero",
                'attack' => 15,
                'defense' => 14,
                'health' => 165,
                'description' => "Un hombre rata sigiloso y rápido, experto en el uso del arco y flechas envenenadas, capaz de infligir daño a sus enemigos desde las sombras.",
                'monster_image_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 43,
                'name' => "Rata ogro",
                'attack' => 20,
                'defense' => 16,
                'health' => 250,
                'description' => "Un hombre rata poderoso y feroz, capaz de enfrentarse a enemigos mucho más grandes que él y salir victorioso.",
                'monster_image_id' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 44,
                'name' => "Portador de oscuridad",
                'attack' => 16,
                'defense' => 14,
                'health' => 190,
                'description' => "Un hombre rata malévolo y astuto, experto en la magia oscura, capaz de manipular las energías del caos para lanzar hechizos destructivos y debilitar a sus enemigos.",
                'monster_image_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 45,
                'name' => "Corredor de alcantarillas",
                'attack' => 22,
                'defense' => 15,
                'health' => 180,
                'description' => "Un hombre rata letal y silencioso, especializado en asesinatos y emboscadas, utilizando sus habilidades para infiltrarse en las filas enemigas y eliminar a sus objetivos sin ser detectado.",
                'monster_image_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 46,
                'name' => "Loboarcano Gigante",
                'attack' => 19,
                'defense' => 15,
                'health' => 290,
                'description' => "Un hombre lobo enorme y temible, armado con un báculo místico que le permite canalizar poderosas energías mágicas, combinando su fuerza bruta con una sorprendente destreza arcanista.",
                'monster_image_id' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 47,
                'name' => "Zal'Koroth, el Colosal",
                'attack' => 21,
                'defense' => 16,
                'health' => 320,
                'description' => "Zal'Koroth, el Colosal, es un hombre lagarto de proporciones gigantescas que blande una lanza igual de imponente. Su habilidad en combate y su fuerza sobrehumana lo convierten en una fuerza aterradora en el campo de batalla.",
                'monster_image_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 48,
                'name' => "Gor'thak el Dezpedazador",
                'attack' => 22,
                'defense' => 15,
                'health' => 280,
                'description' => "Gor'thak el Dezpedazador es un orco gigante y aterrador, armado con un hacha masiva y un casco adornado con cuernos temibles. Su ferocidad y fuerza abrumadora lo convierten en un enemigo prácticamente imparable en el campo de batalla.",
                'monster_image_id' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 49,
                'name' => "Cráneo espectral",
                'attack' => 18,
                'defense' => 15,
                'health' => 200,
                'description' => "El Espectro del Cráneo es una figura siniestra y encapuchada, portando un báculo con forma de calavera que le otorga poderes sobrenaturales. Invoca terribles maldiciones y controla a las criaturas de la noche para sembrar el miedo en sus enemigos.",
                'monster_image_id' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 50,
                'name' => "Golem Árbol Abrasado",
                'attack' => 20,
                'defense' => 16,
                'health' => 260,
                'description' => "El Golem Árbol Abrasado es una criatura imponente creada a partir de un árbol quemado y carbonizado. Sus ramas retorcidas y su corteza ennegrecida le otorgan una apariencia siniestra, mientras que su fuerza sobrenatural lo convierte en un enemigo temible.",
                'monster_image_id' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 51,
                'name' => "Gólem de Barro",
                'attack' => 16,
                'defense' => 14,
                'health' => 220,
                'description' => "El Gólem de Barro es una criatura elemental de aspecto tosco y primitivo, moldeada a partir de lodo y tierra. Su fuerza bruta y su capacidad de absorber impactos lo convierten en un enemigo resistente y persistente.",
                'monster_image_id' => 51,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 52,
                'name' => "Gólem de Fuego",
                'attack' => 19,
                'defense' => 14,
                'health' => 210,
                'description' => "El Gólem de Fuego es una criatura elemental ardiente, cuyo cuerpo está compuesto por llamas y brasas. Sus ataques infligen daño por fuego a sus enemigos, y su mera presencia puede incendiar el entorno.",
                'monster_image_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 53,
                'name' => "Gólem de Carne Pútrida",
                'attack' => 18,
                'defense' => 15,
                'health' => 240,
                'description' => "El Gólem de Carne Pútrida es una abominación grotesca, creada a partir de restos humanos y animales en descomposición. Su apariencia repugnante y su resistencia sobrenatural lo hacen un enemigo espantoso y difícil de enfrentar.",
                'monster_image_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => "Cubo Gelatinoso",
                'attack' => 17,
                'defense' => 14,
                'health' => 190,
                'description' => "El Cubo Gelatinoso Voraz es una criatura extraña y peligrosa, compuesta de una sustancia viscosa y translúcida. En su interior, alberga armas devoradas de antiguos enemigos, las cuales utiliza para atacar a sus presas de manera impredecible.",
                'monster_image_id' => 54,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 55,
                'name' => "Llama Espectral",
                'attack' => 16,
                'defense' => 14,
                'health' => 170,
                'description' => "La Llama Espectral Azul es un espíritu etéreo y misterioso, que se manifiesta en forma de fuego azul brillante. Sus ataques arcanos y su capacidad de atravesar las defensas físicas la convierten en un adversario difícil de combatir.",
                'monster_image_id' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 56,
                'name' => "Árbol Amistoso",
                'attack' => 18,
                'defense' => 16,
                'health' => 250,
                'description' => "El Gólem Árbol Amistoso es una criatura creada a partir de un árbol sano y vigoroso, y parece ser un guardián pacífico de la naturaleza. Sin embargo, su fuerza sobrenatural y su capacidad de manipular la flora circundante lo convierten en un enemigo peligroso para aquellos que lo subestiman.",
                'monster_image_id' => 56,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 57,
                'name' => "Cofre Trampa",
                'attack' => 20,
                'defense' => 15,
                'health' => 200,
                'description' => "El Cofre Trampa es astuto y engañoso que atrae a los incautos con la promesa de botín valioso. En realidad, es una criatura viva que se alimenta de la energía vital de sus víctimas, utilizando su forma de cofre como una forma de camuflaje.",
                'monster_image_id' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 58,
                'name' => "Gólem de Hielo",
                'attack' => 17,
                'defense' => 14,
                'health' => 220,
                'description' => "El Gólem de Hielo es una criatura elemental con cuerpo de hielo sólido, capaz de congelar a sus enemigos con solo tocarlos. Sus ataques infligen daño por frío y puede crear ventiscas y nevadas para obstaculizar a sus oponentes.",
                'monster_image_id' => 58,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 59,
                'name' => "Gólem de Roca",
                'attack' => 20,
                'defense' => 16,
                'health' => 270,
                'description' => "El Gólem de Roca es una criatura elemental de aspecto imponente, creada a partir de la roca y la piedra. Su piel dura y resistente lo hace un enemigo difícil de vencer, mientras que su gran tamaño y fuerza sobrenatural lo hacen un adversario formidable.",
                'monster_image_id' => 59,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 60,
                'name' => "Hechicera Goblin",
                'attack' => 16,
                'defense' => 12,
                'health' => 180,
                'description' => "La Hechicera Goblin es una criatura astuta y peligrosa, capaz de lanzar poderosos hechizos mágicos para controlar y manipular a sus enemigos. A pesar de su pequeño tamaño y apariencia frágil, su inteligencia y astucia la hacen un adversario temible.",
                'monster_image_id' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 61,
                'name' => "Gólem de Viento",
                'attack' => 19,
                'defense' => 16,
                'health' => 230,
                'description' => "Una criatura elemental compuesta por violentos torbellinos de viento. Es capaz de controlar las corrientes de aire para desorientar y confundir a sus enemigos, y sus ataques pueden desgarrar hasta las pieles más duras.",
                'monster_image_id' => 61,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 62,
                'name' => "Zalthor",
                'attack' => 22,
                'defense' => 18,
                'health' => 300,
                'description' => "Zalthor, el Hechicero Oscuro, es una criatura temible y poderosa, capaz de convocar la oscuridad y la sombra para atacar a sus enemigos. Su tamaño gigantesco lo hace aún más intimidante, y su capacidad para invocar demonios y bestias infernales lo convierten en un adversario prácticamente invencible.",
                'monster_image_id' => 62,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 63,
                'name' => "Kyzar",
                'attack' => 20,
                'defense' => 15,
                'health' => 350,
                'description' => "Kyzar, la Quimera de las Sombras, es una criatura masiva y aterradora que combina elementos de león, cabra y serpiente. Sus garras afiladas, cuernos retorcidos y veneno mortal la hacen un enemigo formidable para cualquier aventurero. Es conocida por acechar en las sombras, atacando con ferocidad y precisión.",
                'monster_image_id' => 63,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 64,
                'name' => "Nagasombra",
                'attack' => 17,
                'defense' => 15,
                'health' => 200,
                'description' => "La Nagasombra es una serpiente venenosa y sigilosa, conocida por acechar a sus presas en la oscuridad. Su piel está cubierta de escamas afiladas y su cola se bifurca en dos puntas letales. Su mordedura es capaz de inyectar veneno mortal en sus víctimas, y puede escabullirse sin ser vista gracias a su habilidad para cambiar de color y camuflarse con su entorno.",
                'monster_image_id' => 64,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 65,
                'name' => "Auriel, el León Alado",
                'attack' => 20,
                'defense' => 16,
                'health' => 250,
                'description' => "Auriel es un majestuoso león alado, con una melena dorada y alas de plumas grises. Es un depredador rápido y letal, capaz de surcar los cielos en busca de su presa. Con sus garras afiladas y sus colmillos feroces, es un enemigo temible para cualquier aventurero que se cruce en su camino.",
                'monster_image_id' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 66,
                'name' => "Espectro de Hielo",
                'attack' => 18,
                'defense' => 14,
                'health' => 200,
                'description' => "Una criatura espectral hecha de frío y oscuridad. Sus garras heladas pueden atravesar incluso la armadura más resistente, y su habilidad para congelar a sus enemigos en su lugar es temida por muchos. Es conocido por aparecer en las noches más frías del invierno, cuando la nieve cubre el suelo y el viento aúlla a través de los árboles.",
                'monster_image_id' => 66,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 67,
                'name' => "Monstruo del Bosque Oscuro",
                'attack' => 16,
                'defense' => 14,
                'health' => 180,
                'description' => "Este monstruo de aspecto humanoide del Bosque Oscuro es una criatura siniestra y peligrosa que acecha entre los árboles. Sus afiladas garras y su capacidad para esconderse en las sombras lo hacen un adversario difícil de enfrentar. A menudo se le describe como un ser malvado y vengativo que se alimenta de la carne de sus presas.",
                'monster_image_id' => 67,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 68,
                'name' => "Beholder",
                'attack' => 22,
                'defense' => 16,
                'health' => 220,
                'description' => "El Beholder es un aterrador ojo flotante gigante, rodeado por una multitud de tentáculos que le permiten flotar y moverse a voluntad. Su capacidad para lanzar rayos mágicos de sus ojos y controlar la mente de sus enemigos lo hacen un enemigo mortal. A menudo se le describe como un ser egoísta y retorcido que busca aumentar su poder y controlar todo lo que lo rodea.",
                'monster_image_id' => 68,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 69,
                'name' => "Grog, el Troll",
                'attack' => 20,
                'defense' => 15,
                'health' => 230,
                'description' => "Grog es un troll de aspecto repulsivo, con una piel cubierta de verrugas y dientes afilados. Es un enemigo formidable en combate, gracias a su fuerza sobrehumana y su capacidad de regeneración. Se le suele encontrar merodeando por los pantanos y las cuevas, buscando su próxima comida o víctima.",
                'monster_image_id' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 70,
                'name' => "Venómica, el Ciempiés Gigante",
                'attack' => 18,
                'defense' => 14,
                'health' => 220,
                'description' => "Venómica es un cienpiés gigante, una criatura que habita en las profundidades de las cavernas. Con su gran número de patas y su mordedura venenosa, es capaz de desgarrar a sus víctimas con facilidad. Su tamaño y fuerza la hacen un enemigo temible para cualquier aventurero.",
                'monster_image_id' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 71,
                'name' => "La Devoradora",
                'attack' => 16,
                'defense' => 14,
                'health' => 190,
                'description' => "La Devoradora es una arpía, una criatura alada con la cabeza y el torso de una mujer y las garras y las alas de un ave de presa. Es conocida por su agilidad y velocidad en el aire, así como por su voz hipnótica que atrae a sus víctimas hacia su muerte segura. Su hambre insaciable la lleva a devorar cualquier cosa que pueda encontrar, incluso seres humanos.",
                'monster_image_id' => 71,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 72,
                'name' => "Frost",
                'attack' => 20,
                'defense' => 15,
                'health' => 280,
                'description' => "Frost es un troll de las nieves, una criatura solitaria que habita en los paisajes nevados. Es conocido por su gran tamaño y su fuerza sobrehumana, así como por su capacidad para resistir las condiciones más frías. Su piel gruesa y su regeneración acelerada lo hacen un enemigo temible en combate.",
                'monster_image_id' => 72,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 73,
                'name' => "Troll del Arrecife",
                'attack' => 18,
                'defense' => 14,
                'health' => 230,
                'description' => "El Troll del Arrecife es una criatura acuática que habita en los arrecifes de coral. Con su gran tamaño y sus garras afiladas, es capaz de desgarrar a sus víctimas sin esfuerzo. A menudo se le describe como un ser solitario y vengativo que acecha en las profundidades marinas.",
                'monster_image_id' => 73,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 74,
                'name' => "Garr",
                'attack' => 18,
                'defense' => 14,
                'health' => 200,
                'description' => "Garr es un hombre bestia del bosque, una criatura que combina la apariencia de un humano y un animal. Con sus garras afiladas y su gran agilidad, es capaz de moverse sin ser detectado en los bosques y atacar a sus presas sin previo aviso. A menudo se le describe como un ser solitario y peligroso, que defiende ferozmente su territorio.",
                'monster_image_id' => 74,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 75,
                'name' => "Ojo de Fuego",
                'attack' => 22,
                'defense' => 15,
                'health' => 260,
                'description' => "Ojo de Fuego es un cíclope, una criatura con un solo ojo en el centro de su frente. Con su gran fuerza y su tamaño imponente, es capaz de aplastar a sus enemigos con facilidad. A menudo se le describe como un ser solitario que habita en las montañas y cuevas más remotas.",
                'monster_image_id' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 76,
                'name' => "Globb",
                'attack' => 14,
                'defense' => 14,
                'health' => 180,
                'description' => "Globby es una criatura con forma de bola de gelatina, una masa viscosa y pegajosa que se mueve por el suelo. Aunque aparenta ser inofensiva, es capaz de absorber a sus víctimas y disolverlas lentamente en su interior. A menudo se le describe como una criatura que habita en los lugares más oscuros y húmedos, esperando a su próxima presa.",
                'monster_image_id' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 77,
                'name' => "Panoram",
                'attack' => 16,
                'defense' => 14,
                'health' => 210,
                'description' => "Panoram es un espíritu del bosque oscuro con cornamenta de cabra, una criatura mística que protege los bosques de los peligros externos. Aunque parece frágil, es capaz de invocar poderosos hechizos y convocar a las criaturas del bosque para que luchen a su lado. A menudo se le describe como una criatura sabia y misteriosa que sólo aparece ante aquellos que respetan la naturaleza.",
                'monster_image_id' => 77,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 78,
                'name' => "Azulor",
                'attack' => 20,
                'defense' => 16,
                'health' => 250,
                'description' => "Azulor es un gran oso azul, una criatura imponente que habita en los bosques nevados. Con su gran fuerza y su pelaje grueso, es capaz de resistir las temperaturas más bajas y aplastar a sus enemigos con facilidad. A menudo se le describe como un ser solitario y feroz, que defiende ferozmente su territorio.",
                'monster_image_id' => 78,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 79,
                'name' => "Rocasol",
                'attack' => 22,
                'defense' => 15,
                'health' => 280,
                'description' => "Rocasol es un trol de roca con melena dorada, una criatura imponente que vive en las montañas más altas. Con su piel gruesa y su gran fuerza, es capaz de resistir los golpes más duros y atacar con gran ferocidad. A menudo se le describe como una criatura solitaria y territorial, que no permite que nadie se acerque a su hogar.",
                'monster_image_id' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 80,
                'name' => "Frostbane",
                'attack' => 20,
                'defense' => 16,
                'health' => 250,
                'description' => "Frostbane es un trol de hielo, una criatura que habita en las regiones más frías y heladas del mundo. Con su piel gruesa y sus garras afiladas, es capaz de resistir el frío extremo y atacar con gran ferocidad. A menudo se le describe como una criatura solitaria y salvaje, que no permite que nadie se acerque a su hogar.",
                'monster_image_id' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'name' => "Golpeador",
                'attack' => 22,
                'defense' => 15,
                'health' => 280,
                'description' => "Golpeador es un trol de la montaña con una porra enorme, una criatura imponente que habita en las montañas más altas. Con su gran fuerza y su arma pesada, es capaz de causar gran daño a sus enemigos. A menudo se le describe como una criatura territorial y agresiva, que no permite que nadie se acerque a su territorio sin una buena razón.",
                'monster_image_id' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 82,
                'name' => "Doscabezas",
                'attack' => 20,
                'defense' => 16,
                'health' => 250,
                'description' => "Doscabezas es un trol bicéfalo, una criatura única y aterradora que se encuentra en las zonas más salvajes del mundo. Con su gran tamaño y su doble cabeza, es capaz de vigilar todo lo que ocurre a su alrededor y atacar con gran ferocidad. A menudo se le describe como una criatura solitaria y peligrosa, que no permite que nadie se acerque demasiado a sus dominios.",
                'monster_image_id' => 82,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 83,
                'name' => "Mente Devoradora",
                'attack' => 16,
                'defense' => 14,
                'health' => 200,
                'description' => "Mente Devoradora es un cerebro con patas, una criatura aterradora que se alimenta de las mentes de sus víctimas. Con su gran tamaño y su capacidad de control mental, es capaz de influir en las mentes de aquellos que se acercan demasiado. A menudo se le describe como una criatura solitaria y peligrosa, que vive en lugares oscuros y olvidados.",
                'monster_image_id' => 83,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 84,
                'name' => "Cabeza Carmesí",
                'attack' => 18,
                'defense' => 14,
                'health' => 220,
                'description' => "Un pájaro gigante de cabeza roja y cuerpo color esmeralda, una criatura hermosa y peligrosa que habita en los lugares más altos del mundo. Con su gran envergadura y su pico afilado, es capaz de atacar con gran ferocidad a aquellos que se acercan demasiado. A menudo se le describe como una criatura territorial y solitaria, que no permite que nadie invada su espacio aéreo sin una buena razón.",
                'monster_image_id' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 85,
                'name' => "Gorgona",
                'attack' => 20,
                'defense' => 15,
                'health' => 240,
                'description' => "Una criatura aterradora que se encuentra en los lugares más oscuros y olvidados del mundo. Con su mirada y su capacidad de petrificación, es capaz de detener a aquellos que se acercan demasiado. A menudo se le describe como una criatura solitaria y peligrosa, que no permite que nadie se acerque demasiado sin una buena razón.",
                'monster_image_id' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 87,
                'name' => "Barro",
                'attack' => 14,
                'defense' => 14,
                'health' => 160,
                'description' => "Barro es una criatura viscosa y gelatinosa, que se mueve arrastrándose por el suelo. Es una criatura peligrosa porque es difícil de matar, y porque se alimenta de cualquier cosa que se cruce en su camino. A menudo se le describe como una criatura sin inteligencia ni emoción, que solo busca saciar su hambre insaciable.",
                'monster_image_id' => 87,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 88,
                'name' => "Ojo Sangriento",
                'attack' => 18,
                'defense' => 15,
                'health' => 200,
                'description' => "Ojo Sangriento es una criatura espeluznante que se caracteriza por su gran tamaño y su única visión. Es un monstruo sigiloso y astuto que acecha en las sombras y en los lugares oscuros. Con su mirada ensangrentada y su habilidad para camuflarse en el ambiente, es capaz de sorprender a cualquiera que se acerque demasiado. A menudo se le describe como una criatura solitaria y peligrosa, que no permite que nadie se acerque demasiado sin una buena razón.",
                'monster_image_id' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 89,
                'name' => "Golgor",
                'attack' => 21,
                'defense' => 16,
                'health' => 280,
                'description' => "Golgor es el Líder de los Trolls, una criatura temible y poderosa que lidera a su raza con mano firme. Con dos cabezas y una lanza, es capaz de causar estragos en sus enemigos, mientras que su capa lo protege de cualquier ataque. A menudo se le describe como una criatura inteligente y astuta, que no se deja engañar fácilmente. Es el terror de las aldeas y los poblados cercanos, y muchos le temen por su ferocidad y su falta de compasión.",
                'monster_image_id' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 90,
                'name' => "Perro siniestro",
                'attack' => 17,
                'defense' => 14,
                'health' => 180,
                'description' => "El Siniestro Perro Cimarrón es una criatura salvaje y peligrosa que se encuentra en los bosques más oscuros y tenebrosos. Se dice que es un perro gigante con un pelaje oscuro y ojos rojos que brillan en la oscuridad. Es un cazador experto y a menudo viaja en manadas para aumentar su fuerza y ​​sus posibilidades de éxito. A menudo se le describe como una criatura muy inteligente y astuta, que sabe cómo aprovechar su entorno para cazar y atrapar a su presa. Si te encuentras con uno de estos perros, ten cuidado: es probable que no te deje escapar con vida.",
                'monster_image_id' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 91,
                'name' => "Pesadilla",
                'attack' => 19,
                'defense' => 15,
                'health' => 200,
                'description' => "Pesadilla es un caballo oscuro con ojos rojos y crines de fuego. Es una criatura terrorífica que se dice que es capaz de llevar a su jinete a través de los reinos de la muerte y el terror. Muchos dicen que es un animal mágico, capaz de manipular la realidad a su voluntad. Su velocidad es legendaria, y es capaz de superar cualquier obstáculo. Si te encuentras con Pesadilla, ten cuidado: es probable que te lleve a un lugar del que nunca podrás regresar.",
                'monster_image_id' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 92,
                'name' => "Hongo Intimidante",
                'attack' => 16,
                'defense' => 14,
                'health' => 180,
                'description' => "El Hongo Intimidante es una criatura extraña y peligrosa. Se trata de un hongo gigante con ojos que parecen mirarte fijamente. Se dice que esta criatura es capaz de controlar las mentes de aquellos que se acercan demasiado, haciendo que se sientan paralizados y confundidos. Es un depredador formidable que utiliza su capacidad para controlar las mentes de sus presas para acercarse y atacar. Si te encuentras con un Hongo Intimidante, ten cuidado: su control mental puede ser peligroso y letal.",
                'monster_image_id' => 92,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 93,
                'name' => "Águila Bestial",
                'attack' => 20,
                'defense' => 14,
                'health' => 220,
                'description' => "El Águila Bestial es una criatura aterradora con la cabeza y las patas delanteras de un águila y las patas traseras de una bestia. Es una criatura que se dice que habita en las cumbres más altas de las montañas y que es muy difícil de encontrar. Es un depredador formidable que utiliza su agilidad y su velocidad para cazar a sus presas. Si te encuentras con un Águila Bestial, ten cuidado: sus garras afiladas y su pico pueden infligir daños mortales.",
                'monster_image_id' => 93,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 94,
                'name' => "Seta Venenosa",
                'attack' => 14,
                'defense' => 14,
                'health' => 160,
                'description' => "La Seta Venenosa es una criatura extraña y peligrosa. Se trata de una pequeña seta que se ha vuelto viva y es capaz de moverse y atacar. Se dice que esta criatura es muy venenosa y que puede causar alucinaciones y confusión. Es un depredador astuto que utiliza su capacidad para crear esporas venenosas para debilitar a sus presas antes de atacarlas. Si te encuentras con una Seta Venenosa Viva, ten cuidado: su veneno puede ser peligroso y letal.",
                'monster_image_id' => 94,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 95,
                'name' => "Hombre de las Nieves",
                'attack' => 18,
                'defense' => 16,
                'health' => 220,
                'description' => "El Hombre de las Nieves es una criatura mítica que se dice que habita en las montañas más altas y en las regiones más frías del mundo. Se trata de una criatura muy alta y musculosa, cubierta de pelo blanco y grueso para resistir el frío extremo. Es un depredador formidable que utiliza su fuerza y su resistencia para cazar a sus presas en las condiciones más duras. Si te encuentras con un Hombre de las Nieves, ten cuidado: es una criatura peligrosa y difícil de vencer.",
                'monster_image_id' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 96,
                'name' => "Habitante del Bosque",
                'attack' => 16,
                'defense' => 14,
                'health' => 180,
                'description' => "Habita en los bosques más antiguos y oscuros de la región. Se trata de una criatura fornida pero ágil, cubierta de piel marrón grisácea para camuflarse en su entorno. Es un depredador astuto que utiliza su habilidad para moverse en silencio y su agilidad para cazar a sus presas. Si te encuentras con un Habitante del Bosque, ten cuidado: es una criatura peligrosa y difícil de ver.",
                'monster_image_id' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 97,
                'name' => "Monstruo de la Laguna",
                'attack' => 20,
                'defense' => 15,
                'health' => 240,
                'description' => "Las leyendas de los pescadores hablan del Monstruo de la Laguna, una criatura acuática que acecha en las profundidades de los lagos más oscuros. Su aspecto es temible, con una piel escamosa y verde que le permite pasar desapercibido en el agua. Sin embargo, son sus colmillos afilados y su fuerza descomunal lo que lo hace verdaderamente peligroso. Pocos han visto al Monstruo de la Laguna y han sobrevivido para contarlo.",
                'monster_image_id' => 97,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 98,
                'name' => "Hombre Escarabajo",
                'attack' => 16,
                'defense' => 14,
                'health' => 190,
                'description' => "Con unas pinzas afiladas, el Hombre Escarabajo se mueve con agilidad en el suelo rocoso. Aunque no es muy fuerte, su velocidad y capacidad de camuflaje lo hacen un oponente difícil de detectar y evitar. Si te aventuras en las profundidades de la cueva, ten cuidado de no cruzarte con él o podrías arrepentirte.",
                'monster_image_id' => 98,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 99,
                'name' => "Ulfric",
                'attack' => 20,
                'defense' => 16,
                'health' => 220,
                'description' => "De garras afiladas y dientes sobresalientes, es un oponente formidable en la lucha cuerpo a cuerpo. Es conocido por ser feroz y astuto, y su aullido a la luna llena aterroriza a los viajeros. Si te encuentras con Ulfric, ten cuidado, su odio hacia los humanos es legendaria y no dudará en atacar si se siente amenazado.",
                'monster_image_id' => 99,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 100,
                'name' => "Sombra del Castillo",
                'attack' => 18,
                'defense' => 14,
                'health' => 180,
                'description' => "Se dice que fue creada en los laboratorios del castillo por los antiguos dueños, utilizando magia negra y tecnología arcana. Con su piel lila y sus ojos vacíos, es una vista aterradora para cualquiera que se cruce en su camino. Es robusto y sigilosa, y su capacidad para desvanecerse en las sombras la hace un enemigo peligroso para cualquier aventurero que se atreva a explorar los alrededores del castillo.",
                'monster_image_id' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 101,
                'name' => "Drak'thar",
                'attack' => 20,
                'defense' => 16,
                'health' => 300,
                'description' => "Drak'thar es una criatura gigante con aspecto reptiloide que se arrastra por los pantanos y las marismas. Su piel gruesa y escamosa es resistente a la mayoría de los ataques, y sus garras afiladas son capaces de cortar carne y huesos. Se dice que tiene un agudo sentido del olfato y puede rastrear a sus presas a kilómetros de distancia. Cualquier viajero que se encuentre con Drak'thar debería mantenerse alerta y preparado para una batalla difícil.",
                'monster_image_id' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 102,
                'name' => "Voltarion",
                'attack' => 20,
                'defense' => 15,
                'health' => 340,
                'description' => "Este colosal centurión espectral se cree que fue creado por los dioses antiguos para proteger sus templos. Su armadura es gruesa y resistente, y su casco está decorado con símbolos sagrados. Porta un rayo por arma que puede lanzar a sus enemigos con gran precisión. Aunque es lento en el movimiento, es capaz de infligir daños tremendos en una sola carga. Se dice que ha protegido santuarios sagrados durante siglos, y que cualquier intruso que se atreva a profanar su tierra será destruido sin piedad.",
                'monster_image_id' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 103,
                'name' => "Azzaroth, el Ave Celestial",
                'attack' => 18,
                'defense' => 14,
                'health' => 260,
                'description' => "Azzaroth, el Ave Celestial, es una majestuosa criatura de enormes proporciones, con plumas azules iridiscentes y una llamativa cola roja. Sus alas imponentes crean ráfagas de viento cuando despliega todo su esplendor. A pesar de su tamaño, Azzaroth es ágil y rápido en el aire, lo que le permite evadir a sus enemigos con facilidad. Su pico afilado y garras temibles pueden infligir un daño significativo a aquellos que se atrevan a desafiarlo. Se dice que su canto puede ser escuchado a lo largo de kilómetros, y aquellos que lo escuchan saben que deben tener cuidado con su presencia.",
                'monster_image_id' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 104,
                'name' => "Esqueleto Guerrero",
                'attack' => 14,
                'defense' => 14,
                'health' => 160,
                'description' => "Este antiguo guerrero reanimado es una visión aterradora. Con sus huesos desgastados y su armadura roída, el Esqueleto Guerrero continúa luchando incluso después de la muerte. A pesar de su apariencia frágil, es un enemigo ágil y persistente que no descansará hasta derrotar a sus adversarios.",
                'monster_image_id' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 105,
                'name' => "Esqueleto Escudero",
                'attack' => 14,
                'defense' => 16,
                'health' => 180,
                'description' => "El Esqueleto Escudero es un sirviente eterno que protege a sus compañeros no-muertos en la batalla. Aunque su ataque no es muy fuerte, su resistente escudo y habilidad para bloquear golpes lo convierten en un oponente desafiante para cualquiera que intente enfrentarse a él y a sus aliados.",
                'monster_image_id' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 106,
                'name' => "Momia Durmiente",
                'attack' => 18,
                'defense' => 14,
                'health' => 280,
                'description' => "La Momia Durmiente parece inofensiva a primera vista, pero una vez despierta de su sueño eterno, se convierte en un enemigo mortífero. Su cuerpo momificado esconde una fuerza sobrenatural y una resistencia sorprendente. Aunque se mueve lentamente, su poderoso ataque es suficiente para infundir temor en el corazón de cualquier aventurero.",
                'monster_image_id' => 106,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 107,
                'name' => "Zombi Errante",
                'attack' => 16,
                'defense' => 14,
                'health' => 200,
                'description' => "El Zombi Errante es una criatura desdichada, moviéndose lentamente con un hambre insaciable de carne. Aunque su apariencia está en descomposición, su fuerza sigue siendo una amenaza para aquellos que se crucen en su camino.",
                'monster_image_id' => 107,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 108,
                'name' => "Zombi Voraz",
                'attack' => 18,
                'defense' => 15,
                'health' => 240,
                'description' => "El Zombi Voraz es una bestia implacable, siempre en busca de su próxima presa. Sus mordiscos y arañazos pueden infligir daños severos, y su resistencia lo hace un oponente difícil de derribar.",
                'monster_image_id' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 109,
                'name' => "Esqueleto Desarmado",
                'attack' => 14,
                'defense' => 14,
                'health' => 160,
                'description' => "Aunque carece de armas, este esqueleto sigue siendo un adversario tenaz. Sus manos huesudas son capaces de asestar golpes dolorosos, y su persistencia en la lucha es sorprendente.",
                'monster_image_id' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 110,
                'name' => "Zombi Arrastrado",
                'attack' => 15,
                'defense' => 14,
                'health' => 180,
                'description' => "Este zombi se arrastra por el suelo con sus extremidades maltrechas, pero no permitas que su apariencia te engañe. Aunque su velocidad es reducida, su ataque sorprende a aquellos que lo subestiman, dejándolos vulnerables.",
                'monster_image_id' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 111,
                'name' => "Momia Resucitada",
                'attack' => 20,
                'defense' => 16,
                'health' => 300,
                'description' => "La Momia Resucitada ha sido devuelta a la vida por fuerzas oscuras, y ahora busca venganza. Su poder aumentado y su capacidad para resistir los ataques la convierten en un enemigo formidable en combate.",
                'monster_image_id' => 111,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 112,
                'name' => "Ojo Espectral Flotante",
                'attack' => 18,
                'defense' => 14,
                'health' => 170,
                'description' => "Este espeluznante ojo flotante es una entidad sobrenatural que vigila en silencio, emitiendo un aura escalofriante. Su ataque psíquico es capaz de causar estragos en la mente de sus enemigos, debilitándolos desde adentro.",
                'monster_image_id' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 113,
                'name' => "Espectro Encapuchado",
                'attack' => 22,
                'defense' => 16,
                'health' => 260,
                'description' => "El Espectro Encapuchado es un espíritu oscuro y misterioso que acecha en las sombras. Con su guadaña etérea, es capaz de segar el alma de sus enemigos, haciéndolo un adversario temible para cualquier aventurero.",
                'monster_image_id' => 113,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 114,
                'name' => "Zombi Mutilado",
                'attack' => 14,
                'defense' => 14,
                'health' => 200,
                'description' => "A pesar de haber perdido varias extremidades, este zombi mutilado no ha renunciado a su sed de carne. Aunque lento, es capaz de atacar con una ferocidad sorprendente, demostrando que sigue siendo una amenaza.",
                'monster_image_id' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 115,
                'name' => "Momia Arquera",
                'attack' => 16,
                'defense' => 14,
                'health' => 240,
                'description' => "La Momia Arquera combina la habilidad de un arquero con la fuerza sobrenatural de una momia. Sus flechas, imbuidas con energía oscura, pueden atravesar incluso las armaduras más resistentes.",
                'monster_image_id' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 116,
                'name' => "Escarabajo Dorado",
                'attack' => 20,
                'defense' => 15,
                'health' => 300,
                'description' => "Este escarabajo de caparazón dorado es una criatura imponente y rara. Su coraza brillante es casi impenetrable, y sus mandíbulas son capaces de triturar armaduras y huesos con facilidad. Su apariencia es engañosa, ya que se mueve rápidamente en la batalla.",
                'monster_image_id' => 116,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 117,
                'name' => "Necrófago",
                'attack' => 18,
                'defense' => 14,
                'health' => 210,
                'description' => "Una criatura aterradora que se alimenta de carne humana. Con sus garras y dientes afilados, puede desgarrar a sus enemigos con facilidad. Su apariencia grotesca y su velocidad en combate lo convierten en un adversario temible.",
                'monster_image_id' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 118,
                'name' => "Mano Cortada",
                'attack' => 14,
                'defense' => 14,
                'health' => 160,
                'description' => "Esta mano cortada, reanimada por energías oscuras, se arrastra por el suelo buscando a sus víctimas. Aunque pequeña, su fuerza y persistencia la convierten en un enemigo sorprendentemente difícil de derrotar.",
                'monster_image_id' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 119,
                'name' => "Sabueso No Muerto",
                'attack' => 20,
                'defense' => 15,
                'health' => 240,
                'description' => "Este Sabueso No Muerto es una bestia temible que ha sido reanimada por fuerzas oscuras. Con su olfato agudo y su mordida poderosa, es un enemigo formidable para aquellos que osan enfrentarlo.",
                'monster_image_id' => 119,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 120,
                'name' => "Momia Vengativa",
                'attack' => 18,
                'defense' => 16,
                'health' => 280,
                'description' => "La Momia Vengativa ha sido despertada de su sueño eterno, y busca venganza contra aquellos que la perturbaron. Con fuerza y resistencia sobrenaturales, es una amenaza formidable para cualquier aventurero.",
                'monster_image_id' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 121,
                'name' => "Murciélago Gigante",
                'attack' => 16,
                'defense' => 14,
                'health' => 180,
                'description' => "Este Murciélago Gigante aterroriza a los aventureros con sus alas enormes y su capacidad de ataque desde el aire. Su mordida y sus garras son letales, y su habilidad para atacar rápidamente lo hace un enemigo difícil de esquivar.",
                'monster_image_id' => 121,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'name' => "Vladisar",
                'attack' => 22,
                'defense' => 16,
                'health' => 320,
                'description' => "Este poderoso nigromante es conocido por su capacidad de controlar a los muertos y manipular las fuerzas oscuras. Armado con un báculo místico y una corona que refuerza sus poderes, Vladisar es un enemigo temible y astuto, no subestimes su capacidad para causar estragos en el campo de batalla.",
                'monster_image_id' => 122,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 123,
                'name' => "Amenkharis, Rey de los No Muertos",
                'attack' => 22,
                'defense' => 16,
                'health' => 300,
                'description' => "Amenkharis, el Rey de los No Muertos, fue alguna vez un poderoso faraón egipcio. Ahora, ha renacido como un gobernante inmortal que controla a legiones de criaturas no muertas. Con aspecto de dios egipcio y poderes sobrenaturales, Amenkharis es un enemigo aterrador que no muestra misericordia ante aquellos que se oponen a su reinado.",
                'monster_image_id' => 123,
                'created_at' => now(),
                'updated_at' => now(),
            ],







            // [
            //     'id' => 1,
            //     'name' => "Grimmhorn",
            //     'attack' => 15,
            //     'defense' => 12,
            //     'health' => 200,
            //     'description' => "A towering minotaur with razor-sharp horns and a fierce temper.",
            //     'monster_image_id' => 5,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 2,
            //     'name' => "Necrotongue",
            //     'attack' => 7,
            //     'defense' => 8,
            //     'health' => 80,
            //     'description' => "A foul-mouthed zombie with a penchant for biting and a surprising amount of speed.",
            //     'monster_image_id' => 12,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 3,
            //     'name' => "Gargoyle Shadowwing",
            //     'attack' => 18,
            //     'defense' => 16,
            //     'health' => 250,
            //     'description' => "A winged stone demon with glowing red eyes and talons that can tear through steel.",
            //     'monster_image_id' => 18,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 4,
            //     'name' => "Frostbite",
            //     'attack' => 12,
            //     'defense' => 10,
            //     'health' => 150,
            //     'description' => "A frosty undead warrior with a sword made of ice and the ability to freeze enemies with a touch.",
            //     'monster_image_id' => 28,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 5,
            //     'name' => "Chimera",
            //     'attack' => 20,
            //     'defense' => 18,
            //     'health' => 300,
            //     'description' => "A mythical beast with the head of a lion, body of a goat, and tail of a serpent, capable of spitting acid and breathing fire.",
            //     'monster_image_id' => 32,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 6,
            //     'name' => "Basilisk",
            //     'attack' => 14,
            //     'defense' => 12,
            //     'health' => 180,
            //     'description' => "A serpentine monster with venomous breath and the ability to turn enemies to stone with a gaze.",
            //     'monster_image_id' => 45,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 7,
            //     'name' => "Hellhound",
            //     'attack' => 10,
            //     'defense' => 8,
            //     'health' => 120,
            //     'description' => "A demonic canine with blazing eyes and a bite that can set foes on fire.",
            //     'monster_image_id' => 22,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'id' => 8,
            //     'name' => "Wyvern",
            //     'attack' => 16,
            //     'defense' => 12,
            //     'health' => 120,
            //     'description' => "A winged dragon with a venomous tail and the ability to breathe blasts of fire.",
            //     'monster_image_id' => 79,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ]);
    }
}
